export const GENRES = ['All', 'Rock', 'Electronic', 'Jazz', 'Classical', 'Pop', 'Hip-Hop']

export const EVENTS = [
  {
    id: 'e01',
    artist: 'Cigarettes After Sex',
    tour: 'X World Tour',
    genre: 'Pop',
    venue: '台北流行音樂中心',
    city: 'Taipei',
    date: '2026-04-11',
    doors: '19:00',
    start: '20:00',
    img: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',
    featured: true,
    soldOut: false,
    tickets: [
      { id: 't1', name: 'General',  price: 1800, total: 2000, sold: 1200 },
      { id: 't2', name: 'Premium',  price: 2800, total: 500,  sold: 380  },
      { id: 't3', name: 'VIP',      price: 4500, total: 100,  sold: 60   },
    ],
    about: 'Cigarettes After Sex 以夢幻的氛圍搖滾聞名，Greg Gonzalez 的聲線如絲般柔軟，配上模糊的吉他音色，構成一種介於深夜與黎明之間的聽覺體驗。',
  },
  {
    id: 'e02',
    artist: 'Floating Points',
    tour: 'Cascade Live',
    genre: 'Electronic',
    venue: 'Legacy Taipei',
    city: 'Taipei',
    date: '2026-04-18',
    doors: '20:00',
    start: '21:00',
    img: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80',
    featured: false,
    soldOut: false,
    tickets: [
      { id: 't1', name: 'Early Bird', price: 900,  total: 300, sold: 300 },
      { id: 't2', name: 'Advance',    price: 1200, total: 600, sold: 340 },
      { id: 't3', name: 'Door',       price: 1500, total: 200, sold: 40  },
    ],
    about: 'Sam Shepherd 以 Floating Points 之名，結合爵士、靈魂樂與電子音樂，創造出極為個人化的聲音語言。此次 Cascade 巡演將帶來完整的現場樂團版本。',
  },
  {
    id: 'e03',
    artist: 'Arooj Aftab',
    tour: 'Night Reign Tour',
    genre: 'Jazz',
    venue: '國家音樂廳',
    city: 'Taipei',
    date: '2026-04-25',
    doors: '19:30',
    start: '20:30',
    img: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&q=80',
    featured: true,
    soldOut: false,
    tickets: [
      { id: 't1', name: 'B 區',  price: 1200, total: 400,  sold: 280 },
      { id: 't2', name: 'A 區',  price: 1800, total: 300,  sold: 200 },
      { id: 't3', name: 'S 區',  price: 2500, total: 100,  sold: 55  },
    ],
    about: '巴基斯坦裔音樂人 Arooj Aftab 以融合烏爾都詩歌、古典聲樂與爵士編排的獨特風格，榮獲葛萊美最佳新藝人提名。此次台灣首演為 Night Reign 巡演亞洲站。',
  },
  {
    id: 'e04',
    artist: 'Fontaines D.C.',
    tour: 'Romance Tour',
    genre: 'Rock',
    venue: 'The Wall',
    city: 'Taipei',
    date: '2026-05-02',
    doors: '19:00',
    start: '20:00',
    img: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=1200&q=80',
    featured: false,
    soldOut: true,
    tickets: [
      { id: 't1', name: 'General', price: 1600, total: 800, sold: 800 },
    ],
    about: '都柏林後龐克樂團 Fontaines D.C. 以詩意的歌詞和凌厲的現場能量見稱，最新專輯 Romance 是他們迄今最大膽的聲音實驗。',
  },
  {
    id: 'e05',
    artist: 'Hiroshi Yoshimura',
    tour: 'Music for Nine Post Offices',
    genre: 'Electronic',
    venue: '台北當代藝術館',
    city: 'Taipei',
    date: '2026-05-09',
    doors: '18:00',
    start: '19:00',
    img: 'https://images.unsplash.com/photo-1549213783-8284d0336c4f?w=1200&q=80',
    featured: false,
    soldOut: false,
    tickets: [
      { id: 't1', name: 'Advance', price: 800,  total: 200, sold: 120 },
      { id: 't2', name: 'Door',    price: 1000, total: 100, sold: 20  },
    ],
    about: '向日本環境音樂先驅 Hiroshi Yoshimura 致敬的重現演出，由策展團隊重新詮釋其代表作 Music for Nine Post Offices，以沉浸式音響裝置呈現。',
  },
  {
    id: 'e06',
    artist: 'Mk.gee',
    tour: 'Two Star World Tour',
    genre: 'Pop',
    venue: 'CLBC',
    city: 'Taipei',
    date: '2026-05-16',
    doors: '20:00',
    start: '21:00',
    img: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&q=80',
    featured: false,
    soldOut: false,
    tickets: [
      { id: 't1', name: 'General', price: 1400, total: 600, sold: 350 },
      { id: 't2', name: 'VIP',     price: 2800, total: 50,  sold: 28  },
    ],
    about: 'Mk.gee 以其在吉他音色上的創新探索和頗具辨識度的嗓音，成為當下最受矚目的新生代創作人之一。Two Star 是他的首張主流廠牌專輯。',
  },
  {
    id: 'e07',
    artist: 'Vijay Iyer Trio',
    tour: 'Compassion Tour',
    genre: 'Jazz',
    venue: '國家演奏廳',
    city: 'Taipei',
    date: '2026-05-23',
    doors: '19:30',
    start: '20:30',
    img: 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=1200&q=80',
    featured: false,
    soldOut: false,
    tickets: [
      { id: 't1', name: 'B 區', price: 1000, total: 300, sold: 150 },
      { id: 't2', name: 'A 區', price: 1500, total: 200, sold: 80  },
    ],
    about: '葛萊美獎得主 Vijay Iyer 帶領三重奏，以嚴謹的即興精神和深厚的音樂學背景，演繹其最新專輯 Compassion 中的曲目。',
  },
  {
    id: 'e08',
    artist: 'Weyes Blood',
    tour: 'And in the Darkness, Hearts Aglow',
    genre: 'Pop',
    venue: '台北流行音樂中心',
    city: 'Taipei',
    date: '2026-06-06',
    doors: '19:00',
    start: '20:00',
    img: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80',
    featured: true,
    soldOut: false,
    tickets: [
      { id: 't1', name: 'General', price: 1600, total: 1500, sold: 800 },
      { id: 't2', name: 'Premium', price: 2400, total: 400,  sold: 180 },
    ],
    about: 'Natalie Mering 以 Weyes Blood 之名創作的音樂，宛如 70 年代電影原聲帶與當代folk的完美融合。此次巡演帶來完整的管弦樂編制現場版本。',
  },
]

export const getById    = id => EVENTS.find(e => e.id === id)
export const getFeatured = () => EVENTS.filter(e => e.featured && !e.soldOut)

export const fmtDate = iso => new Date(iso).toLocaleDateString('zh-TW', {
  year: 'numeric', month: 'long', day: 'numeric', weekday: 'short',
})
export const fmtShort = iso => {
  const d = new Date(iso)
  return {
    mon: d.toLocaleDateString('en-US', { month: 'short' }).toUpperCase(),
    day: String(d.getDate()).padStart(2, '0'),
    wd:  d.toLocaleDateString('zh-TW', { weekday: 'short' }),
  }
}
